services:
  - type: web
    name: elastos
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: BUILD_TIMESTAMP
        generateValue: true
    healthCheckPath: /
    autoDeploy: true 